# Generated by Django 3.2.16 on 2022-11-27 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name of station')),
                ('status', models.CharField(choices=[('BR', 'broken'), ('RG', 'running')], default='RG', editable=False, max_length=2, verbose_name='Station status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Start date')),
                ('broke_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date of breakdown')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=100, verbose_name='X-axis coordinate')),
                ('y', models.IntegerField(default=100, verbose_name='Y-axis coordinate')),
                ('z', models.IntegerField(default=100, verbose_name='Z-axis coordinate')),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='space_station.station')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.CharField(choices=[('X', 'x'), ('Y', 'y'), ('Z', 'z')], max_length=1, verbose_name='Axis')),
                ('distance', models.IntegerField(verbose_name='Distance')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='space_station.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instruction',
                'verbose_name_plural': 'Instructions',
            },
        ),
    ]
